main: me.PSK1103.VariablePortalSizes.VariablePortalSizes
name: VariablePortalSizes
api-version: "1.14"
version: 1.0.0

author: PSK1103

permissions:
  variableportalsizes.reload:
    default: op

commands:
  variableportalsizes:
    description: Reloads config
    aliases: [vps, variableportalsizes]
    usage: /vps reload